### ISSUE TITLE
Readme has typo in "uses" for "Get IP Addresses"

### ISSUE THREAD

**Issue by alexandzors** [candidob/get-runner-ip#1]
```yml
...
        steps:
            - name: Get IP Addresses
              id: ip
              uses: candidob@get-runner-ip@v1.0.0
...
```

Should be:

```yml
...
        steps:
            - name: Get IP Addresses
              id: ip
              uses: candidob/get-runner-ip@v1.0.0
...
```
